services:
  zookeeper:
    image: bitnami/zookeeper:latest
    restart: unless-stopped
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper

# bitnami kafka komutları direk /bin içerisindedir.
# kafka-topics.sh --create --topic inventory-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
# kafka-topics.sh --create --topic shipping-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
# kafka-topics.sh --create --topic sms-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1
# kafka-topics.sh --create --topic email-topic --bootstrap-server localhost:9092 --partitions 1 --replication-factor 1